### ISSUE TITLE
SnackBar is shown above opened navigation drawer

### ISSUE THREAD

**Issue by Lingviston** [nispok/snackbar#63] opened 2015-01-08 12:27 UTC
I have Fragment which contains ListView placed as DrawerLayout content view. I create a Snackbar instance inside Fragment and attach it to my ListView. Then I open the drawer and Snackbar is displayed above it. In GMail app Snackbar is displayed below the opened drawer. Can I achieve similar behavior somehow?

**Comment by wmora** [comment] 2015-01-09 00:51
Not with the current implementation, but applying the change suggested in #62 would solve this

**Comment by wmora** [comment] 2015-01-11 22:20
will close this as dupe of #62

**Closed by wmora** 2015-01-11 22:20 UTC
Labels: duplicate
