### ISSUE TITLE
Adjust For Navigation Bar.

### ISSUE THREAD

**Issue by JonathanMerritt** [nispok/snackbar#45] opened 2014-12-17 13:51 UTC
Great lib!

Is there a way to adjust the snackbar position according to the navbars visibility?

Thanks,
Jon.

**Comment by JonathanMerritt** [comment] 2015-01-10 07:47
Totally unrelated @wmora.

I was curious if swipe down to dismiss is possible? Like in Gmail for example.

Thanks.

**Comment by wmora** [comment] 2015-01-10 12:55
@JonathanMerritt Not right now. We already have an issue for this (#51). Haven't had time to implement it, though.

**Comment by JonathanMerritt** [comment] 2015-01-10 13:03
Sorry for not searching for it. I usually do. Just got lazy.

I actually noticed it isn't a swipe down in Gmail. It is dismissed for any outside touch. So I don't think that it's anything to implement. Obviously that's your call.

It does feel more natural. But I don't mind not having it.

Thanks.

**Comment by cargo8** [comment] 2015-01-12 18:23
Hello,

I don't think your positioning / offsetting of the Snackbar logic is correct. I'm using a Droid Turbo and the snackbar appears with an apparent offset of navBarHeight (but there is no software nav bar so it is awkwardly floating in the screen).

Wasn't sure if I should file a separate issue as it is likely related to this question / issue.

Thanks

**Comment by JonathanMerritt** [comment] 2015-01-12 18:26
That was my issue. I had my nav set to translucent mode. So when it wasn't there, from when I took my soft nav off, the sbar hovered as if it thought it was there.

Tried some things bit nothing worked. So I unset translucent mode and it now sets in the right place with or without the navbar.

Not sure if a flag for translucency is possible or something. Idk.

**Comment by wmora** [comment] 2015-01-12 20:06
@cargo8 which Android version is your phone running?

**Comment by chrislacy** [comment] 2015-01-12 23:13
FYI here's a gist of how I get the Snackbar displaying correctly with a translucent nav bar (and also of a smaller width on tablets): https://gist.github.com/chrislacy/a0e082a4cf46c5166c2b

I've been meaning to integrate the changes properly as a pull request but haven't had the time. HTH.

**Comment by cargo8** [comment] 2015-01-13 03:23
@wmora I am on 4.4.4 on Droid Turbo, but remember that this device has capacitative keys (not software keys)

**Comment by JonathanMerritt** [comment] 2015-01-13 07:39
That fix works great for me @chrislacy

Hopefully it can be integrated into the library.

**Comment by wmora** [comment] 2015-01-13 12:29
@cargo8 oh, right! that's why!

@chrislacy thanks for the gist! @cargo8 could you test it with your phone?

**Comment by cargo8** [comment] 2015-01-13 22:31
@wmora it kind of works (in that the snackbar is ultimately positioned correctly), but the animation still goes to the wrong place, then the margin is set and it jumps down

**Comment by chrislacy** [comment] 2015-01-13 22:33
FYI it works fine for me. Although I'm still using version 2.1.1.

**Comment by cargo8** [comment] 2015-01-13 22:48
@wmora this is a bit hacky, but how I was able to fix it 

 @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    private boolean isNavigationBarHidden(ViewGroup root) {

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
            return false;
        }

        int viewFlags = root.getWindowSystemUiVisibility();
        return hasSoftwareButtons() &&
                (viewFlags & View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION) ==
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION;
    }

    private boolean hasSoftwareButtons() {
        boolean hasBackKey = KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_BACK);
        boolean hasHomeKey = KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_HOME);
        return !hasBackKey && !hasHomeKey;
    }

**Comment by chrislacy** [comment] 2015-01-13 22:50
Why not use
http://developer.android.com/reference/android/view/View.html#fitSystemWindows(android.graphics.Rect)
?

**Comment by cargo8** [comment] 2015-01-13 23:19
@chrislacy I'm not sure that would fix my issue, the problem is that when you DO NOT have software keys (i.e. has hardware keys), the snackbar still sets a bottom margin to offset for it.

As I understand it, fitSystemWindows(...) would just ensure that it does not get overlapped in the case I DO have software keys.

**Comment by JonathanMerritt** [comment] 2015-01-14 00:24
I have hardware keys(sgs3) on a custom rom. So if I set my navbar on or off, that gist worked for me.

Actually my last 'fix' where I just unset translucent mode, it worked without the gist included. Never had issues with my hardware keys interfering.

**Comment by wmora** [comment] 2015-02-11 23:28
fixed in [2.9.0](https://github.com/nispok/snackbar/releases/tag/v2.9.0)

**Closed by wmora** 2015-02-11 23:28 UTC
Labels: question
